# Generated by GitHub Copilot
# Container Apps module — hosts backend app + LangFuse observability service
#
# Uses Consumption plan (scale-to-zero) to minimise costs when idle.
# System-assigned Managed Identity is used for all Azure service auth.
#
# NOTE: This module does NOT create a Log Analytics workspace.
# The workspace created by the monitoring module is passed in via
# var.log_analytics_workspace_id to avoid duplicate resource names.

resource "azurerm_container_app_environment" "main" {
  name                       = "cae-research-${var.suffix}"
  location                   = var.location
  resource_group_name        = var.resource_group_name
  log_analytics_workspace_id = var.log_analytics_workspace_id
  tags                       = var.tags
}

# ── Backend Container App ─────────────────────────────────────────────────────
resource "azurerm_container_app" "backend" {
  name                         = "ca-research-backend-${var.suffix}"
  container_app_environment_id = azurerm_container_app_environment.main.id
  resource_group_name          = var.resource_group_name
  revision_mode                = "Single"
  tags                         = var.tags

  # System-assigned Managed Identity — used for RBAC to OpenAI, Key Vault, ACR
  identity {
    type = "SystemAssigned"
  }

  registry {
    server   = var.acr_login_server
    identity = "system"
  }

  template {
    min_replicas = 0  # Scale to zero when idle
    max_replicas = 3

    container {
      name   = "backend"
      image  = "${var.acr_login_server}/research-agent:${var.image_tag}"
      cpu    = 0.5
      memory = "1Gi"

      # Environment variables — secrets fetched from Key Vault at runtime
      env {
        name  = "APP_ENV"
        value = "production"
      }
      env {
        name  = "AZURE_OPENAI_ENDPOINT"
        value = var.openai_endpoint
      }
      env {
        name  = "POSTGRES_HOST"
        value = var.postgres_host
      }
      env {
        name  = "REDIS_URL"
        value = var.redis_url
      }
      env {
        name  = "AZURE_KEY_VAULT_URL"
        value = var.key_vault_url
      }
      env {
        name  = "APPLICATIONINSIGHTS_CONNECTION_STRING"
        value = var.app_insights_conn_string
      }
      env {
        name  = "ENABLE_AUTH"
        value = "true"
      }
      env {
        name  = "ENABLE_SAFETY"
        value = "true"
      }
    }

    http_scale_rule {
      name                = "http-scaler"
      concurrent_requests = "10"
    }
  }

  ingress {
    external_enabled           = true
    target_port                = 8000
    transport                  = "http"
    allow_insecure_connections = false

    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }
}

# ── LangFuse Container App (self-hosted LLM observability) ───────────────────
resource "azurerm_container_app" "langfuse" {
  name                         = "ca-langfuse-${var.suffix}"
  container_app_environment_id = azurerm_container_app_environment.main.id
  resource_group_name          = var.resource_group_name
  revision_mode                = "Single"
  tags                         = var.tags

  template {
    min_replicas = 0
    max_replicas = 1

    container {
      name   = "langfuse"
      image  = "langfuse/langfuse:latest"
      cpu    = 0.5
      memory = "1Gi"

      env {
        name  = "DATABASE_URL"
        value = var.langfuse_db_url
      }
      env {
        name  = "NEXTAUTH_SECRET"
        value = var.langfuse_secret
      }
      env {
        name  = "NEXTAUTH_URL"
        value = "https://ca-langfuse-${var.suffix}.${azurerm_container_app_environment.main.default_domain}"
      }
      env {
        name  = "TELEMETRY_ENABLED"
        value = "false"
      }
    }
  }

  ingress {
    external_enabled           = true
    target_port                = 3000
    transport                  = "http"
    allow_insecure_connections = false

    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }
}

output "backend_url" {
  value = "https://${azurerm_container_app.backend.ingress[0].fqdn}"
}

output "app_identity_principal_id" {
  value = azurerm_container_app.backend.identity[0].principal_id
}

output "langfuse_url" {
  value = "https://${azurerm_container_app.langfuse.ingress[0].fqdn}"
}

variable "resource_group_name" {}
variable "location" {}
variable "suffix" {}
variable "tags" { type = map(string) }
variable "acr_login_server" {}
variable "acr_id" {}
variable "openai_endpoint" {}
variable "postgres_host" {}
variable "redis_url" {}
variable "key_vault_url" {}
variable "app_insights_conn_string" {}
variable "log_analytics_workspace_id" {}
variable "image_tag" { default = "latest" }
variable "langfuse_db_url" {
  default = ""
}
variable "langfuse_secret" {
  default   = ""
  sensitive = true
}
