# Generated by GitHub Copilot
"""
Azure client factory — created once at app startup via FastAPI lifespan.

Security principle: DefaultAzureCredential is used for ALL Azure services.
  - In production (Container Apps): uses Managed Identity — zero credentials
  - In local dev: falls back to AZURE_CLIENT_ID/SECRET from .env
  - No API key is ever stored in code or passed as a constructor argument
    for Azure services. The only exception is Tavily (external SaaS).

All clients are stored in app.state and injected via FastAPI's dependency
injection — no global singletons that make testing harder.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import AsyncGenerator

from azure.identity.aio import DefaultAzureCredential
from fastapi import FastAPI
from langchain_openai import AzureChatOpenAI
from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver
from tavily import AsyncTavilyClient

from app.backend.core.config import get_settings

logger = logging.getLogger(__name__)

# Module-level references — set during lifespan startup
_llm: AzureChatOpenAI | None = None
_tavily: AsyncTavilyClient | None = None
_graph_checkpointer: AsyncPostgresSaver | None = None
_credential: DefaultAzureCredential | None = None


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    """
    FastAPI lifespan: initialise all Azure clients on startup, close on shutdown.
    Using lifespan (not @app.on_event) is the current FastAPI best practice.
    """
    global _llm, _tavily, _graph_checkpointer, _credential

    settings = get_settings()
    logger.info("Initialising Azure clients (env=%s)", settings.app_env)

    # ── Azure credential (Managed Identity in prod, env vars locally) ─────────
    _credential = DefaultAzureCredential()

    # ── LangChain AzureChatOpenAI ─────────────────────────────────────────────
    # azure_ad_token_provider uses Managed Identity — no API key needed in prod.
    # If AZURE_OPENAI_API_KEY is set (local dev), LangChain uses that instead.
    # LangFuse callback is attached here so every LLM call is traced automatically.
    from azure.identity import get_bearer_token_provider
    from azure.identity import DefaultAzureCredential as SyncCredential
    from app.backend.core.telemetry import get_langfuse_handler

    # Attach LangFuse callback if configured (traces all LLM calls)
    lf_handler = get_langfuse_handler()
    callbacks = [lf_handler] if lf_handler else []

    if settings.azure_openai_api_key:
        # Local dev: use API key
        _llm = AzureChatOpenAI(
            azure_endpoint=settings.azure_openai_endpoint,
            azure_deployment=settings.azure_openai_deployment,
            api_version=settings.azure_openai_api_version,
            api_key=settings.azure_openai_api_key,
            temperature=0.1,
            max_tokens=4096,
            callbacks=callbacks,
        )
        logger.info("AzureChatOpenAI initialised with API key (local dev)")
    else:
        # Production: Managed Identity
        token_provider = get_bearer_token_provider(
            SyncCredential(),
            "https://cognitiveservices.azure.com/.default",
        )
        _llm = AzureChatOpenAI(
            azure_endpoint=settings.azure_openai_endpoint,
            azure_deployment=settings.azure_openai_deployment,
            api_version=settings.azure_openai_api_version,
            azure_ad_token_provider=token_provider,
            temperature=0.1,
            max_tokens=4096,
            callbacks=callbacks,
        )
        logger.info("AzureChatOpenAI initialised with Managed Identity")

    # ── Tavily client ─────────────────────────────────────────────────────────
    # API key fetched from Key Vault in production; from .env locally.
    tavily_key = await _get_secret_or_env("TAVILY_API_KEY", settings.tavily_api_key)
    _tavily = AsyncTavilyClient(api_key=tavily_key)
    logger.info("Tavily client initialised")

    # ── PostgreSQL checkpointer (LangGraph state persistence) ─────────────────
    _graph_checkpointer = AsyncPostgresSaver.from_conn_string(settings.postgres_dsn)
    await _graph_checkpointer.setup()  # creates checkpoint tables if needed
    logger.info("PostgreSQL checkpointer ready at %s:%d", settings.postgres_host, settings.postgres_port)

    # Store in app state for dependency injection
    app.state.llm = _llm
    app.state.tavily = _tavily
    app.state.checkpointer = _graph_checkpointer
    app.state.credential = _credential

    logger.info("All Azure clients ready — application startup complete")
    yield

    # ── Shutdown ──────────────────────────────────────────────────────────────
    logger.info("Closing Azure clients")
    if _credential:
        await _credential.close()
    if _graph_checkpointer:
        await _graph_checkpointer.conn.close()


async def _get_secret_or_env(secret_name: str, env_fallback: str) -> str:
    """
    In production: fetch secret from Azure Key Vault.
    In local dev: use environment variable fallback.
    """
    settings = get_settings()
    if settings.azure_key_vault_url and _credential:
        try:
            from azure.keyvault.secrets.aio import SecretClient
            kv_client = SecretClient(
                vault_url=settings.azure_key_vault_url,
                credential=_credential,
            )
            secret = await kv_client.get_secret(secret_name.lower().replace("_", "-"))
            await kv_client.close()
            return secret.value or env_fallback
        except Exception as e:
            logger.warning("Could not fetch %s from Key Vault, using env fallback: %s", secret_name, e)
    return env_fallback


# ── Accessor functions (used by agents and tools) ────────────────────────────

def get_llm() -> AzureChatOpenAI:
    if _llm is None:
        raise RuntimeError("LLM not initialised — lifespan not started")
    return _llm


def get_tavily_client() -> AsyncTavilyClient:
    if _tavily is None:
        raise RuntimeError("Tavily client not initialised — lifespan not started")
    return _tavily


def get_checkpointer() -> AsyncPostgresSaver:
    if _graph_checkpointer is None:
        raise RuntimeError("Checkpointer not initialised — lifespan not started")
    return _graph_checkpointer
