# Generated by GitHub Copilot
"""
Application settings — Pydantic Settings reads from environment variables.

In production: env vars are injected by Azure Container Apps from Key Vault
references (no secrets ever in container image or GitHub).
In local dev: .env file is loaded automatically by pydantic-settings.

Feature flags control optional enterprise features:
  ENABLE_AUTH      — Entra ID JWT validation (default off for local dev)
  ENABLE_CACHE     — Redis semantic result cache
  ENABLE_SAFETY    — Azure AI Content Safety gates
  ENABLE_LANGFUSE  — LLM trace shipping to self-hosted LangFuse
"""

from __future__ import annotations

from functools import lru_cache

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # ── App ───────────────────────────────────────────────────────────────────
    app_env: str = Field(default="development", pattern="^(development|staging|production)$")
    log_level: str = "INFO"
    allowed_origins: list[str] = Field(default=["http://localhost:5173", "http://localhost:3001"])

    # ── Azure OpenAI ──────────────────────────────────────────────────────────
    azure_openai_endpoint: str = ""
    azure_openai_api_version: str = "2024-10-21"
    azure_openai_deployment: str = "gpt-4o"
    # Local dev only — in production this field is empty; Managed Identity is used
    azure_openai_api_key: str = ""

    # ── Key Vault ─────────────────────────────────────────────────────────────
    azure_key_vault_url: str = ""

    # ── PostgreSQL (LangGraph checkpointer) ──────────────────────────────────
    postgres_host: str = "localhost"
    postgres_port: int = 5432
    postgres_db: str = "research_agent"
    postgres_user: str = "research_user"
    postgres_password: str = ""

    @property
    def postgres_dsn(self) -> str:
        return (
            f"postgresql://{self.postgres_user}:{self.postgres_password}"
            f"@{self.postgres_host}:{self.postgres_port}/{self.postgres_db}"
        )

    # ── Redis ─────────────────────────────────────────────────────────────────
    redis_url: str = "redis://localhost:6379/0"
    cache_ttl_seconds: int = 3600

    # ── Tavily ────────────────────────────────────────────────────────────────
    tavily_api_key: str = ""

    # ── LangFuse (self-hosted LLM observability) ──────────────────────────────
    langfuse_host: str = "http://localhost:3000"
    langfuse_public_key: str = ""
    langfuse_secret_key: str = ""

    # ── Azure Application Insights ────────────────────────────────────────────
    applicationinsights_connection_string: str = ""

    # ── Azure Content Safety ──────────────────────────────────────────────────
    azure_content_safety_endpoint: str = ""
    azure_content_safety_key: str = ""

    # ── Entra ID Auth ─────────────────────────────────────────────────────────
    azure_auth_tenant_id: str = ""
    azure_auth_client_id: str = ""
    azure_auth_audience: str = ""

    # ── Rate limiting ─────────────────────────────────────────────────────────
    rate_limit_per_minute: int = 20
    max_tokens_per_request: int = 10000

    # ── Feature flags ─────────────────────────────────────────────────────────
    enable_auth: bool = False
    enable_cache: bool = True
    enable_safety: bool = True
    enable_langfuse: bool = True

    @field_validator("allowed_origins", mode="before")
    @classmethod
    def parse_origins(cls, v: str | list) -> list[str]:
        if isinstance(v, str):
            return [o.strip() for o in v.split(",")]
        return v

    @property
    def is_production(self) -> bool:
        return self.app_env == "production"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return cached settings singleton. Cached after first call."""
    return Settings()
