# Generated by GitHub Copilot
"""
Content safety gate — Azure AI Content Safety (input + output screening).

Two gates in the request lifecycle:
  Gate 1 (input): before LangGraph executes — blocks harmful queries
  Gate 2 (output): after synthesis — checks final report before returning

Pattern note: In enterprise, Gate 2 is often at the APIM layer (inbound/outbound
policy). Gate 1 is always in the application because APIM can't inspect the
full business context of a research query.
"""

from __future__ import annotations

import logging

from fastapi import HTTPException, status

from app.backend.core.config import get_settings

logger = logging.getLogger(__name__)

# Azure AI Content Safety severity threshold (0=safe, 2=low, 4=medium, 6=high)
_BLOCK_SEVERITY_THRESHOLD = 4


async def check_input_safety(text: str) -> None:
    """
    Gate 1: Check user query for harmful content before research begins.
    Raises HTTP 400 if content violates safety policy.
    """
    settings = get_settings()
    if not settings.enable_safety:
        return

    if not settings.azure_content_safety_endpoint:
        logger.warning("Content safety endpoint not configured — skipping safety check")
        return

    try:
        from azure.ai.contentsafety.aio import ContentSafetyClient
        from azure.ai.contentsafety.models import AnalyzeTextOptions
        from azure.core.credentials import AzureKeyCredential

        credential = AzureKeyCredential(settings.azure_content_safety_key)
        async with ContentSafetyClient(
            endpoint=settings.azure_content_safety_endpoint,
            credential=credential,
        ) as client:
            request = AnalyzeTextOptions(text=text[:1000])
            response = await client.analyze_text(request)

        # Block if any category exceeds threshold
        categories = {
            "Hate": response.hate_result.severity if response.hate_result else 0,
            "Violence": response.violence_result.severity if response.violence_result else 0,
            "SelfHarm": response.self_harm_result.severity if response.self_harm_result else 0,
            "Sexual": response.sexual_result.severity if response.sexual_result else 0,
        }

        for category, severity in categories.items():
            if severity >= _BLOCK_SEVERITY_THRESHOLD:
                logger.warning("Content safety blocked query: category=%s severity=%d", category, severity)
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail=f"Query blocked by content safety policy ({category}).",
                )

    except HTTPException:
        raise
    except Exception as e:
        # Do not block on content safety service errors — log and continue
        logger.error("Content safety check failed (non-blocking): %s", e)
