# Generated by GitHub Copilot
"""
Rate limiting — per-user, JWT-aware, Redis-backed.

Uses slowapi (Starlette-compatible rate limiter wrapping limits library).
Rate limit key is the JWT 'oid' claim (Entra ID object ID).
This ensures users behind the same corporate NAT each get individual limits —
not the shared IP address.

When auth is disabled (local dev): falls back to IP-based limiting.
"""

from __future__ import annotations

from fastapi import Request
from slowapi import Limiter
from slowapi.util import get_remote_address

from app.backend.core.config import get_settings


def _get_rate_limit_key(request: Request) -> str:
    """
    Extract rate limit key from request.
    - With auth: use JWT 'oid' claim (unique per user, not per IP)
    - Without auth: use client IP address
    """
    # Check if JWT user context was attached by the auth middleware
    user_id: str | None = getattr(request.state, "user_id", None)
    if user_id:
        return user_id
    # Fallback: IP address (local dev / auth disabled)
    return get_remote_address(request)


settings = get_settings()

# Redis storage URI keeps rate limit counters distributed across pod replicas.
# Falls back to in-memory if Redis is unavailable (dev-only behaviour).
limiter = Limiter(
    key_func=_get_rate_limit_key,
    storage_uri=settings.redis_url,
    default_limits=[f"{settings.rate_limit_per_minute}/minute"],
)
