# Generated by GitHub Copilot
"""
Observability setup — OpenTelemetry + LangFuse.

Two parallel observability streams:
  1. OpenTelemetry → Azure Application Insights
     Infrastructure telemetry: HTTP request traces, response times,
     error rates, custom metrics (tokens, cost). This is the same
     instrumentation pattern as Datadog at Accenture — swap the exporter
     to point at a Datadog Agent and the code is unchanged.

  2. LangFuse (self-hosted on Azure Container Apps)
     LLM-specific telemetry: every prompt, response, tool call, token
     count, and agent chain. Data stays inside Azure. This replaces
     LangSmith SaaS which would send traces to a 3rd-party endpoint.

Interview answer for "how do you handle observability in LLM apps?":
  "OTel for infrastructure — same code whether the backend is Azure Monitor
  or Datadog. LangFuse self-hosted for LLM traces — because prompts and
  responses are sensitive data that cannot leave the Azure perimeter."
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from app.backend.core.config import get_settings

if TYPE_CHECKING:
    from langfuse.callback import CallbackHandler

logger = logging.getLogger(__name__)

# Global LangFuse handler — set during setup_telemetry(), used by azure_clients.py
_langfuse_handler: "CallbackHandler | None" = None


def get_langfuse_handler() -> "CallbackHandler | None":
    """Return the global LangFuse callback handler (None if disabled/unconfigured)."""
    return _langfuse_handler


def setup_telemetry() -> None:
    """
    Initialise OpenTelemetry exporter + LangFuse callback.
    Called once during app startup (before lifespan creates Azure clients).
    """
    settings = get_settings()
    _setup_opentelemetry(settings)
    _setup_langfuse(settings)


def _setup_opentelemetry(settings) -> None:
    """Configure OpenTelemetry → Azure Application Insights."""
    if not settings.applicationinsights_connection_string:
        logger.info("App Insights connection string not set — OTel disabled")
        return

    try:
        from azure.monitor.opentelemetry import configure_azure_monitor
        configure_azure_monitor(
            connection_string=settings.applicationinsights_connection_string,
            logger_name="research_intelligence_agent",
        )
        logger.info("OpenTelemetry → Azure App Insights configured")

        # Auto-instrument FastAPI (HTTP request/response traces)
        from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
        FastAPIInstrumentor().instrument()

        # Auto-instrument httpx (outgoing HTTP calls to Tavily, APIs)
        from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor
        HTTPXClientInstrumentor().instrument()

    except Exception as e:
        logger.warning("OTel setup failed (non-blocking): %s", e)


def _setup_langfuse(settings) -> None:
    """
    Configure LangFuse for LLM trace collection.

    LangFuse integrates with LangChain via a CallbackHandler.
    The handler is stored globally and passed to the LLM in azure_clients.py.
    This ensures every LLM call, tool call, and agent step is traced.

    Data stays inside your Azure subscription — LangFuse is self-hosted.
    This is the enterprise-correct alternative to LangSmith SaaS.
    """
    global _langfuse_handler

    if not settings.enable_langfuse:
        logger.info("LangFuse disabled via ENABLE_LANGFUSE=false")
        return

    if not settings.langfuse_public_key or not settings.langfuse_secret_key:
        logger.info("LangFuse credentials not set — LLM tracing disabled")
        return

    try:
        from langfuse.callback import CallbackHandler

        _langfuse_handler = CallbackHandler(
            public_key=settings.langfuse_public_key,
            secret_key=settings.langfuse_secret_key,
            host=settings.langfuse_host,
        )
        logger.info(
            "LangFuse callback handler ready (host=%s) — will be attached to LLM in azure_clients",
            settings.langfuse_host,
        )

    except Exception as e:
        logger.warning("LangFuse setup failed (non-blocking): %s", e)
