# Generated by GitHub Copilot
# Azure Monitor — Log Analytics + Application Insights

resource "azurerm_log_analytics_workspace" "main" {
  name                = "law-research-${var.suffix}"
  location            = var.location
  resource_group_name = var.resource_group_name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = var.tags
}

resource "azurerm_application_insights" "main" {
  name                = "appi-research-${var.suffix}"
  location            = var.location
  resource_group_name = var.resource_group_name
  workspace_id        = azurerm_log_analytics_workspace.main.id
  application_type    = "web"
  tags                = var.tags
}

output "app_insights_connection_string" {
  value     = azurerm_application_insights.main.connection_string
  sensitive = true
}
output "app_insights_id"              { value = azurerm_application_insights.main.id }
output "log_analytics_workspace_id"  { value = azurerm_log_analytics_workspace.main.id }

variable "resource_group_name" {}
variable "location" {}
variable "suffix" {}
variable "tags" { type = map(string) }
