# Generated by GitHub Copilot
# Azure PostgreSQL Flexible Server — LangGraph checkpoint storage

resource "azurerm_postgresql_flexible_server" "main" {
  name                   = "psql-research-${var.suffix}"
  location               = var.location
  resource_group_name    = var.resource_group_name
  version                = "16"
  administrator_login    = "pgadmin"
  administrator_password = var.admin_password
  # Burstable B1ms — cheapest tier, suitable for portfolio/dev
  sku_name               = "B_Standard_B1ms"
  storage_mb             = 32768
  backup_retention_days  = 7
  tags                   = var.tags
}

resource "azurerm_postgresql_flexible_server_database" "research" {
  name      = "research_agent"
  server_id = azurerm_postgresql_flexible_server.main.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}

# Allow Azure services (Container Apps) to connect
resource "azurerm_postgresql_flexible_server_firewall_rule" "azure_services" {
  name             = "allow-azure-services"
  server_id        = azurerm_postgresql_flexible_server.main.id
  start_ip_address = "0.0.0.0"
  end_ip_address   = "0.0.0.0"
}

output "fqdn" { value = azurerm_postgresql_flexible_server.main.fqdn }
output "id"   { value = azurerm_postgresql_flexible_server.main.id }

variable "resource_group_name" {}
variable "location" {}
variable "suffix" {}
variable "tags" { type = map(string) }
variable "admin_password" {
  sensitive = true
}
