# Generated by GitHub Copilot
# Root Terraform module — orchestrates all Azure resources
#
# Deploys:
#   - Azure Container Apps environment + app (backend)
#   - Azure Container Apps (LangFuse self-hosted)
#   - Azure Container Registry (ACR)
#   - Azure PostgreSQL Flexible Server (LangGraph checkpointer)
#   - Azure Cache for Redis (rate limiter + semantic cache)
#   - Azure Key Vault (secrets)
#   - Azure OpenAI (GPT-4o)
#   - Azure Application Insights + Log Analytics
#   - Azure API Management (Consumption tier — AI Gateway)
#   - RBAC role assignments (Managed Identity → services)

terraform {
  required_version = ">= 1.7"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
  # Remote state — Azure Blob Storage backend
  # Uncomment and fill in after creating storage account manually (one-time bootstrap)
  # backend "azurerm" {
  #   resource_group_name  = "rg-tfstate"
  #   storage_account_name = "<your_storage_account>"
  #   container_name       = "tfstate"
  #   key                  = "research-agent.terraform.tfstate"
  # }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy    = false
      recover_soft_deleted_key_vaults = true
    }
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

resource "random_string" "suffix" {
  length  = 6
  special = false
  upper   = false
}

locals {
  suffix   = random_string.suffix.result
  rg_name  = "rg-research-agent-${var.environment}"
  location = var.location
  tags = {
    project     = "research-intelligence-agent"
    environment = var.environment
    managed_by  = "terraform"
  }
}

resource "azurerm_resource_group" "main" {
  name     = local.rg_name
  location = local.location
  tags     = local.tags
}

# ── Modules ───────────────────────────────────────────────────────────────────

module "monitoring" {
  source              = "./modules/monitoring"
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  suffix              = local.suffix
  tags                = local.tags
}

module "key_vault" {
  source              = "./modules/key_vault"
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  suffix              = local.suffix
  tags                = local.tags
  # Pass secret values (set in terraform.tfvars — never in git)
  tavily_api_key      = var.tavily_api_key
}

module "openai" {
  source              = "./modules/openai"
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  suffix              = local.suffix
  tags                = local.tags
}

module "postgres" {
  source              = "./modules/postgres"
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  suffix              = local.suffix
  tags                = local.tags
  admin_password      = var.postgres_admin_password
}

module "redis" {
  source              = "./modules/redis"
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  suffix              = local.suffix
  tags                = local.tags
}

module "container_registry" {
  source              = "./modules/container_registry"
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  suffix              = local.suffix
  tags                = local.tags
}

module "container_apps" {
  source                     = "./modules/container_apps"
  resource_group_name        = azurerm_resource_group.main.name
  location                   = local.location
  suffix                     = local.suffix
  tags                       = local.tags
  acr_login_server           = module.container_registry.login_server
  acr_id                     = module.container_registry.id
  openai_endpoint            = module.openai.endpoint
  postgres_host              = module.postgres.fqdn
  redis_url                  = module.redis.connection_string
  key_vault_url              = module.key_vault.vault_uri
  app_insights_conn_string   = module.monitoring.app_insights_connection_string
  log_analytics_workspace_id = module.monitoring.log_analytics_workspace_id
  image_tag                  = var.image_tag
}

# ── RBAC: Managed Identity → Azure services (zero credentials) ───────────────

# Container App → Azure OpenAI (Cognitive Services User)
resource "azurerm_role_assignment" "app_to_openai" {
  scope                = module.openai.resource_id
  role_definition_name = "Cognitive Services OpenAI User"
  principal_id         = module.container_apps.app_identity_principal_id
}

# Container App → Key Vault (Secrets User)
resource "azurerm_role_assignment" "app_to_keyvault" {
  scope                = module.key_vault.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = module.container_apps.app_identity_principal_id
}

# Container App → ACR (AcrPull — for image pull)
resource "azurerm_role_assignment" "app_to_acr" {
  scope                = module.container_registry.id
  role_definition_name = "AcrPull"
  principal_id         = module.container_apps.app_identity_principal_id
}
