# Generated by GitHub Copilot
# Azure Key Vault — secrets management (Tavily API key, etc.)
#
# Uses RBAC authorization mode (enable_rbac_authorization = true).
# This is consistent with the root module which grants "Key Vault Secrets User"
# to the Container App via azurerm_role_assignment. RBAC and access policies
# are mutually exclusive — you must choose one. RBAC is the modern approach.

data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "main" {
  name                        = "kv-research-${var.suffix}"
  location                    = var.location
  resource_group_name         = var.resource_group_name
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name                    = "standard"
  enable_rbac_authorization   = true   # RBAC mode — uses role assignments, not access policies
  purge_protection_enabled    = false  # set true for production
  soft_delete_retention_days  = 7
  tags                        = var.tags
}

# Grant Terraform deployer "Key Vault Administrator" so it can create secrets.
# (RBAC mode: no access policies allowed — use role assignments instead.)
resource "azurerm_role_assignment" "terraform_deployer_kv" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = "Key Vault Administrator"
  principal_id         = data.azurerm_client_config.current.object_id
}

# Store Tavily API key as a secret
resource "azurerm_key_vault_secret" "tavily_api_key" {
  name         = "tavily-api-key"
  value        = var.tavily_api_key
  key_vault_id = azurerm_key_vault.main.id

  depends_on = [azurerm_role_assignment.terraform_deployer_kv]
}

output "vault_uri" { value = azurerm_key_vault.main.vault_uri }
output "id"        { value = azurerm_key_vault.main.id }

variable "resource_group_name" {}
variable "location" {}
variable "suffix" {}
variable "tags" { type = map(string) }
variable "tavily_api_key" {
  sensitive = true
}
