# Generated by GitHub Copilot
# Azure OpenAI module

resource "azurerm_cognitive_account" "openai" {
  name                = "oai-research-${var.suffix}"
  location            = var.location
  resource_group_name = var.resource_group_name
  kind                = "OpenAI"
  sku_name            = "S0"
  tags                = var.tags

  custom_subdomain_name = "oai-research-${var.suffix}"
}

resource "azurerm_cognitive_deployment" "gpt4o" {
  name                 = "gpt-4o"
  cognitive_account_id = azurerm_cognitive_account.openai.id

  model {
    format  = "OpenAI"
    name    = "gpt-4o"
    version = "2024-11-20"
  }

  sku {
    name     = "GlobalStandard"
    capacity = 30
  }
}

output "endpoint"    { value = azurerm_cognitive_account.openai.endpoint }
output "resource_id" { value = azurerm_cognitive_account.openai.id }

variable "resource_group_name" {}
variable "location" {}
variable "suffix" {}
variable "tags" { type = map(string) }
