# Generated by GitHub Copilot
"""
Pydantic request/response models for the research API.

Keeping models separate from agents/state means the API contract can evolve
independently from the internal LangGraph state structure.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class ResearchRequest(BaseModel):
    """POST /research/start — initiate a new research session."""

    query: str = Field(
        min_length=10,
        max_length=1000,
        description="The research question or topic to investigate.",
        examples=["Analyse NVIDIA's competitive position in the AI chip market for 2025"],
    )


class PlanApprovalRequest(BaseModel):
    """POST /research/{session_id}/approve — approve or reject the research plan."""

    approved: bool = Field(description="True to proceed with research, False to cancel.")
    feedback: str | None = Field(
        default=None,
        max_length=500,
        description="Optional feedback if rejecting the plan.",
    )


class ResearchStatusResponse(BaseModel):
    """GET /research/{session_id}/status — current state of a research session."""

    session_id: str
    status: Literal["planning", "awaiting_approval", "researching", "synthesizing", "complete", "failed"]
    query: str
    created_at: datetime | None = None
    total_tokens_used: int = 0
    total_cost_usd: float = 0.0
    error_message: str | None = None


class ResearchPlanResponse(BaseModel):
    """Returned to client at the interrupt() point for human-in-the-loop approval."""

    session_id: str
    original_query: str
    sub_queries: list[str]
    assigned_agents: list[str]
    estimated_duration_seconds: int
    estimated_tokens: int
    message: str = "Review and approve this plan to begin research."


class ResearchResultResponse(BaseModel):
    """Final response after research completes successfully."""

    session_id: str
    query: str
    final_report: str
    citations: list[dict]
    total_tokens_used: int
    total_cost_usd: float
    agents_used: list[str]
    status: str = "complete"


class HealthResponse(BaseModel):
    """GET /health — liveness probe response."""

    status: Literal["ok", "degraded"]
    version: str = "0.1.0"
    checks: dict[str, bool] = Field(default_factory=dict)
