# Generated by GitHub Copilot
"""
FastAPI application factory.

Wires together:
  - CORS middleware (origins from settings)
  - Rate limiter (slowapi)
  - Request correlation middleware (X-Request-ID → App Insights trace linkage)
  - All API routers
  - OpenAPI docs (disabled in production)
"""

from __future__ import annotations

import logging
import uuid

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from slowapi.errors import RateLimitExceeded
from slowapi.middleware import SlowAPIMiddleware
from starlette.responses import JSONResponse

from app.backend.api.health import router as health_router
from app.backend.api.research import router as research_router
from app.backend.core.azure_clients import lifespan
from app.backend.core.config import get_settings
from app.backend.core.rate_limiter import limiter
from app.backend.core.telemetry import setup_telemetry

logger = logging.getLogger(__name__)


def create_app() -> FastAPI:
    settings = get_settings()

    # Initialise telemetry before app creation
    setup_telemetry()

    app = FastAPI(
        title="Research Intelligence Agent",
        description="Production-grade Multi-Agent Research Platform — LangGraph + LangChain on Azure",
        version="0.1.0",
        lifespan=lifespan,
        # Disable interactive docs in production (security best practice)
        docs_url="/docs" if not settings.is_production else None,
        redoc_url="/redoc" if not settings.is_production else None,
        openapi_url="/openapi.json" if not settings.is_production else None,
    )

    # ── Rate limiter state ────────────────────────────────────────────────────
    app.state.limiter = limiter
    app.add_middleware(SlowAPIMiddleware)
    app.add_exception_handler(RateLimitExceeded, _rate_limit_handler)

    # ── CORS ──────────────────────────────────────────────────────────────────
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.allowed_origins,
        allow_credentials=True,
        allow_methods=["GET", "POST"],
        allow_headers=["Authorization", "Content-Type", "X-Request-ID"],
    )

    # ── Request correlation middleware ────────────────────────────────────────
    @app.middleware("http")
    async def correlation_id_middleware(request: Request, call_next):
        request_id = request.headers.get("X-Request-ID", str(uuid.uuid4()))
        request.state.request_id = request_id
        response = await call_next(request)
        response.headers["X-Request-ID"] = request_id
        return response

    # ── Routers ───────────────────────────────────────────────────────────────
    app.include_router(health_router)
    app.include_router(research_router, prefix="/v1")

    return app


def _rate_limit_handler(request: Request, exc: RateLimitExceeded) -> JSONResponse:
    return JSONResponse(
        status_code=429,
        content={"detail": f"Rate limit exceeded. Retry after {exc.retry_after}s."},
    )
