# Generated by GitHub Copilot
"""Application entry point — starts uvicorn server."""

from __future__ import annotations

import logging
import os

import uvicorn

from app.backend.core.config import get_settings


def main() -> None:
    settings = get_settings()
    logging.basicConfig(
        level=getattr(logging, settings.log_level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    uvicorn.run(
        "app.backend.app:create_app",
        factory=True,
        host="0.0.0.0",  # noqa: S104 — intentional for container binding
        port=int(os.getenv("PORT", "8000")),
        reload=not settings.is_production,
        log_level=settings.log_level.lower(),
        access_log=True,
    )


if __name__ == "__main__":
    main()
