# Generated by GitHub Copilot
"""Health check endpoint — used by Azure Container Apps liveness probe."""

from __future__ import annotations

import logging

from fastapi import APIRouter
from fastapi.responses import JSONResponse

from app.backend.core.azure_clients import get_checkpointer
from app.backend.models.research import HealthResponse

logger = logging.getLogger(__name__)
router = APIRouter(tags=["health"])


@router.get("/health", response_model=HealthResponse)
async def health_check() -> JSONResponse:
    """
    Liveness probe for Azure Container Apps.
    Returns 200 if healthy, 503 if any critical dependency is down.
    """
    checks: dict[str, bool] = {}

    # Check PostgreSQL (checkpointer)
    try:
        checkpointer = get_checkpointer()
        await checkpointer.conn.execute("SELECT 1")
        checks["postgres"] = True
    except Exception as e:
        logger.warning("Health check: PostgreSQL unavailable: %s", e)
        checks["postgres"] = False

    all_healthy = all(checks.values())

    return JSONResponse(
        content=HealthResponse(
            status="ok" if all_healthy else "degraded",
            checks=checks,
        ).model_dump(),
        status_code=200 if all_healthy else 503,
    )
