# Generated by GitHub Copilot
"""
Research API endpoints.

Endpoints:
  POST   /research/start                 — start new session, returns plan for approval
  POST   /research/{session_id}/approve  — approve/reject plan → graph resumes
  GET    /research/{session_id}/stream   — SSE stream of agent events
  GET    /research/{session_id}/status   — poll-based status check
  GET    /research/{session_id}/result   — fetch completed report

SSE streaming pattern:
  graph.astream_events() emits events as each LangGraph node runs.
  We filter for relevant events (node_start, node_end, custom agent updates)
  and push them to the client via Server-Sent Events.
  The client sees: "web_research started" → "market_data started" → ... → "report ready"
"""

from __future__ import annotations

import json
import logging
import uuid
from typing import AsyncGenerator

from fastapi import APIRouter, HTTPException, Request, status
from fastapi.responses import StreamingResponse
from langgraph.types import Command

from app.backend.agents.graph import build_research_graph
from app.backend.agents.state import AgentState
from app.backend.core.azure_clients import get_checkpointer
from app.backend.core.content_safety import check_input_safety
from app.backend.core.rate_limiter import limiter
from app.backend.models.research import (
    PlanApprovalRequest,
    ResearchRequest,
    ResearchResultResponse,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/research", tags=["research"])


@router.post("/start", status_code=status.HTTP_202_ACCEPTED)
@limiter.limit("20/minute")
async def start_research(
    request: Request,
    body: ResearchRequest,
) -> dict:
    """
    Start a new research session.

    1. Validates and safety-screens the query
    2. Generates a unique session_id (LangGraph thread_id)
    3. Runs the graph until interrupt() — supervisor creates plan
    4. Returns the plan for user approval

    The graph is now PAUSED and state is saved to PostgreSQL.
    """
    # ── Input validation + content safety gate ────────────────────────────────
    await check_input_safety(body.query)

    session_id = str(uuid.uuid4())
    user_id = getattr(request.state, "user_id", "anonymous")

    initial_state = AgentState(
        user_query=body.query,
        user_id=user_id,
        session_id=session_id,
        research_plan=None,
        plan_approved=False,
        agent_findings=[],
        synthesis_notes="",
        final_report="",
        citations=[],
        total_tokens_used=0,
        total_cost_usd=0.0,
        error_message=None,
        status="planning",
    )

    checkpointer = get_checkpointer()
    graph = build_research_graph(checkpointer)

    config = {"configurable": {"thread_id": session_id}}

    try:
        # Run until interrupt() — supervisor node creates the plan and pauses
        result = await graph.ainvoke(initial_state, config=config)

        # After interrupt(), state is saved and the graph is paused.
        # The supervisor's interrupt() payload is available in graph state.
        current_state = await graph.aget_state(config)
        interrupt_value = None

        if current_state.tasks:
            for task in current_state.tasks:
                if hasattr(task, "interrupts") and task.interrupts:
                    interrupt_value = task.interrupts[0].value
                    break

        if interrupt_value and interrupt_value.get("type") == "plan_approval":
            plan = interrupt_value["plan"]
            return {
                "session_id": session_id,
                "status": "awaiting_approval",
                "plan": plan,
                "message": "Review the research plan and call POST /research/{session_id}/approve to proceed.",
            }

        # If graph completed without interrupt (e.g., plan creation failed)
        return {
            "session_id": session_id,
            "status": result.get("status", "unknown"),
            "message": result.get("error_message", "Research complete"),
        }

    except Exception as e:
        logger.exception("Failed to start research session=%s: %s", session_id, e)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to start research. Please try again.",
        )


@router.post("/{session_id}/approve")
@limiter.limit("20/minute")
async def approve_plan(
    request: Request,
    session_id: str,
    body: PlanApprovalRequest,
) -> dict:
    """
    Resume the graph after human-in-the-loop plan approval.

    Sends the approval response to the paused interrupt() in supervisor_node.
    The graph then fans out to all research agents in parallel.
    """
    checkpointer = get_checkpointer()
    graph = build_research_graph(checkpointer)
    config = {"configurable": {"thread_id": session_id}}

    # Verify session exists
    state = await graph.aget_state(config)
    if not state or not state.values:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Research session '{session_id}' not found.",
        )

    try:
        # Resume the graph with the approval decision
        # LangGraph resumes from the interrupt() call in supervisor_node
        await graph.ainvoke(
            Command(resume={"approved": body.approved, "feedback": body.feedback}),
            config=config,
        )

        if body.approved:
            return {
                "session_id": session_id,
                "status": "researching",
                "message": "Research agents are now working. Stream updates at GET /research/{session_id}/stream",
            }
        else:
            return {
                "session_id": session_id,
                "status": "failed",
                "message": "Research cancelled.",
            }

    except Exception as e:
        logger.exception("Failed to resume session=%s: %s", session_id, e)
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))


@router.get("/{session_id}/stream")
async def stream_research_events(
    request: Request,
    session_id: str,
) -> StreamingResponse:
    """
    SSE stream of research agent events.

    Streams events as LangGraph nodes execute:
      data: {"event": "agent_start", "agent": "web_research"}
      data: {"event": "agent_complete", "agent": "web_research", "duration": 12.3}
      data: {"event": "synthesis_start"}
      data: {"event": "complete", "session_id": "..."}

    Client uses EventSource API to display live agent progress.
    """
    checkpointer = get_checkpointer()
    graph = build_research_graph(checkpointer)
    config = {"configurable": {"thread_id": session_id}}

    async def event_generator() -> AsyncGenerator[str, None]:
        try:
            async for event in graph.astream_events(None, config=config, version="v2"):
                event_type = event.get("event", "")
                name = event.get("name", "")
                data = event.get("data", {})

                # Filter to meaningful events for the frontend
                if event_type == "on_chain_start" and name in (
                    "web_research", "market_data", "news_sentiment", "synthesis"
                ):
                    yield _sse({"event": "agent_start", "agent": name})

                elif event_type == "on_chain_end" and name in (
                    "web_research", "market_data", "news_sentiment", "synthesis"
                ):
                    output = data.get("output", {})
                    yield _sse({"event": "agent_complete", "agent": name})

                elif event_type == "on_chain_end" and name == "LangGraph":
                    # Entire graph completed
                    output = data.get("output", {})
                    yield _sse({
                        "event": "complete",
                        "session_id": session_id,
                        "status": output.get("status", "complete"),
                    })

                # Disconnect if client closed connection
                if await request.is_disconnected():
                    break

        except Exception as e:
            logger.error("SSE stream error for session=%s: %s", session_id, e)
            yield _sse({"event": "error", "message": str(e)})

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",  # disable nginx buffering
        },
    )


@router.get("/{session_id}/result", response_model=ResearchResultResponse)
async def get_result(session_id: str) -> ResearchResultResponse:
    """Fetch the completed research report for a session."""
    checkpointer = get_checkpointer()
    graph = build_research_graph(checkpointer)
    config = {"configurable": {"thread_id": session_id}}

    state = await graph.aget_state(config)
    if not state or not state.values:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Session not found.")

    values = state.values
    if values.get("status") not in ("complete", "failed"):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Research not complete yet. Current status: {values.get('status')}",
        )

    return ResearchResultResponse(
        session_id=session_id,
        query=values.get("user_query", ""),
        final_report=values.get("final_report", ""),
        citations=values.get("citations", []),
        total_tokens_used=values.get("total_tokens_used", 0),
        total_cost_usd=values.get("total_cost_usd", 0.0),
        agents_used=[f["agent_name"] for f in values.get("agent_findings", [])],
        status=values.get("status", "unknown"),
    )


def _sse(data: dict) -> str:
    """Format a Server-Sent Event string."""
    return f"data: {json.dumps(data)}\n\n"
