# Generated by GitHub Copilot
"""
LangChain tool definitions — Financial data via yfinance (free, no API key).

yfinance wraps Yahoo Finance's unofficial API.
ADR note: For production financial applications requiring real-time, licensed data,
replace with Bloomberg API, Refinitiv Eikon, or Alpha Vantage paid tier.
yfinance is appropriate for a portfolio project demonstrating the pattern.
"""

from __future__ import annotations

import logging

from langchain_core.tools import tool

logger = logging.getLogger(__name__)


@tool
def get_stock_info_tool(ticker: str) -> str:
    """
    Get current stock information for a given ticker symbol.

    Use this to retrieve:
    - Current stock price and daily change
    - Market capitalisation
    - P/E ratio, EPS, dividend yield
    - 52-week high/low
    - Company sector and industry

    Args:
        ticker: Stock ticker symbol (e.g., "AAPL", "MSFT", "NVDA", "TSLA")

    Returns:
        Formatted stock information string
    """
    import yfinance as yf

    try:
        stock = yf.Ticker(ticker.upper().strip())
        info = stock.info

        if not info or info.get("regularMarketPrice") is None:
            return f"No data found for ticker '{ticker}'. Verify the symbol is correct."

        return (
            f"Stock: {info.get('longName', ticker)} ({ticker.upper()})\n"
            f"Price: ${info.get('regularMarketPrice', 'N/A'):.2f}\n"
            f"Change: {info.get('regularMarketChangePercent', 0):.2f}%\n"
            f"Market Cap: ${info.get('marketCap', 0):,.0f}\n"
            f"P/E Ratio: {info.get('trailingPE', 'N/A')}\n"
            f"EPS: {info.get('trailingEps', 'N/A')}\n"
            f"52W High: ${info.get('fiftyTwoWeekHigh', 'N/A')}\n"
            f"52W Low: ${info.get('fiftyTwoWeekLow', 'N/A')}\n"
            f"Sector: {info.get('sector', 'N/A')}\n"
            f"Industry: {info.get('industry', 'N/A')}\n"
            f"Note: Data via Yahoo Finance (15-min delayed)"
        )
    except Exception as e:
        logger.warning("yfinance get_stock_info failed for ticker=%s: %s", ticker, e)
        raise


@tool
def get_stock_history_tool(ticker: str, period: str = "3mo") -> str:
    """
    Get historical stock price data for trend analysis.

    Use this to analyse price trends and performance over time.

    Args:
        ticker: Stock ticker symbol (e.g., "AAPL")
        period: Time period — "1mo", "3mo", "6mo", "1y", "2y"

    Returns:
        Price performance summary with start, end, high, low, and % change
    """
    import yfinance as yf

    try:
        stock = yf.Ticker(ticker.upper().strip())
        hist = stock.history(period=period)

        if hist.empty:
            return f"No historical data found for '{ticker}' over period '{period}'."

        start_price = hist["Close"].iloc[0]
        end_price = hist["Close"].iloc[-1]
        high = hist["High"].max()
        low = hist["Low"].min()
        pct_change = ((end_price - start_price) / start_price) * 100
        avg_volume = hist["Volume"].mean()

        return (
            f"Historical performance for {ticker.upper()} ({period}):\n"
            f"Start price: ${start_price:.2f}\n"
            f"Current price: ${end_price:.2f}\n"
            f"Change: {pct_change:+.2f}%\n"
            f"Period high: ${high:.2f}\n"
            f"Period low: ${low:.2f}\n"
            f"Avg daily volume: {avg_volume:,.0f}\n"
            f"Data points: {len(hist)} trading days"
        )
    except Exception as e:
        logger.warning("yfinance get_stock_history failed for ticker=%s: %s", ticker, e)
        raise


@tool
def get_company_financials_tool(ticker: str) -> str:
    """
    Get key financial metrics for a company (revenue, earnings, cash flow).

    Use this for fundamental financial analysis.

    Args:
        ticker: Stock ticker symbol (e.g., "AAPL")

    Returns:
        Key financial metrics summary
    """
    import yfinance as yf

    try:
        stock = yf.Ticker(ticker.upper().strip())
        info = stock.info

        if not info:
            return f"No financial data found for ticker '{ticker}'."

        return (
            f"Financials for {info.get('longName', ticker)} ({ticker.upper()}):\n"
            f"Revenue (TTM): ${info.get('totalRevenue', 0):,.0f}\n"
            f"Gross Profit: ${info.get('grossProfits', 0):,.0f}\n"
            f"Net Income: ${info.get('netIncomeToCommon', 0):,.0f}\n"
            f"Revenue Growth (YoY): {info.get('revenueGrowth', 0) * 100:.1f}%\n"
            f"Profit Margin: {info.get('profitMargins', 0) * 100:.1f}%\n"
            f"Total Cash: ${info.get('totalCash', 0):,.0f}\n"
            f"Total Debt: ${info.get('totalDebt', 0):,.0f}\n"
            f"Free Cash Flow: ${info.get('freeCashflow', 0):,.0f}\n"
            f"Return on Equity: {info.get('returnOnEquity', 0) * 100:.1f}%\n"
            f"Note: Annual data via Yahoo Finance"
        )
    except Exception as e:
        logger.warning("yfinance get_company_financials failed for ticker=%s: %s", ticker, e)
        raise
