# Generated by GitHub Copilot
"""LangChain tool — News search via Tavily news endpoint."""

from __future__ import annotations

import logging

from langchain_core.tools import tool

logger = logging.getLogger(__name__)


@tool
async def news_search_tool(query: str, days_back: int = 7) -> str:
    """
    Search for recent news articles using Tavily's news-focused search.

    Use this to find:
    - Recent news headlines (last 1-7 days)
    - Press releases and announcements
    - Analyst opinions and market commentary

    Args:
        query: News search query (e.g., "Apple earnings Q1 2025")
        days_back: How many days back to search (1-7, default 7)

    Returns:
        Formatted list of recent news articles with titles, dates, and summaries
    """
    from app.backend.core.azure_clients import get_tavily_client

    try:
        client = get_tavily_client()
        results = await client.search(
            query=query[:400],
            topic="news",
            days=min(days_back, 7),
            max_results=7,
            include_answer=False,
        )

        if not results.get("results"):
            return f"No recent news found for: {query}"

        output_parts = [f"Recent news for '{query}' (last {days_back} days):\n"]
        for i, article in enumerate(results["results"][:7], 1):
            published = article.get("published_date", "Unknown date")
            output_parts.append(
                f"[{i}] {article.get('title', 'No title')}\n"
                f"    Date: {published}\n"
                f"    URL: {article.get('url', '')}\n"
                f"    Summary: {article.get('content', '')[:300]}\n"
            )

        return "\n".join(output_parts)

    except Exception as e:
        logger.warning("Tavily news search failed for query=%r: %s", query[:50], e)
        raise
