# Generated by GitHub Copilot
"""
LangChain tool definitions — Web Search (Tavily).

@tool decorator makes this a first-class LangChain tool.
The LLM reads the docstring to decide when to call it.
Docstring quality directly affects tool selection accuracy.
"""

from __future__ import annotations

import logging

from langchain_core.tools import tool

logger = logging.getLogger(__name__)


@tool
async def web_search_tool(query: str) -> str:
    """
    Search the web for current information using Tavily.

    Use this tool to find:
    - Current news and events
    - Company information and announcements
    - General knowledge and facts
    - Technical documentation or reports

    Args:
        query: A clear, specific search query (max 400 chars)

    Returns:
        Formatted search results with titles, URLs, and content snippets
    """
    from app.backend.core.azure_clients import get_tavily_client

    try:
        client = get_tavily_client()
        results = await client.search(
            query=query[:400],
            search_depth="advanced",
            max_results=5,
            include_answer=True,
        )

        if not results.get("results"):
            return f"No results found for: {query}"

        # Format results for LLM consumption
        output_parts = []
        if results.get("answer"):
            output_parts.append(f"Summary: {results['answer']}\n")

        for i, result in enumerate(results["results"][:5], 1):
            output_parts.append(
                f"[{i}] {result.get('title', 'No title')}\n"
                f"URL: {result.get('url', '')}\n"
                f"Content: {result.get('content', '')[:500]}\n"
            )

        return "\n".join(output_parts)

    except Exception as e:
        logger.warning("Tavily web search failed for query=%r: %s", query[:50], e)
        raise  # Let LangGraph RetryPolicy handle it
