# Generated by GitHub Copilot
"""LangChain tool — Wikipedia factual knowledge lookup (free, no API key)."""

from __future__ import annotations

import logging

from langchain_core.tools import tool

logger = logging.getLogger(__name__)


@tool
def wikipedia_tool(topic: str) -> str:
    """
    Search Wikipedia for factual background information on a topic.

    Use this to find:
    - Company history and background
    - Technical definitions and explanations
    - Historical events and context
    - Industry overviews

    Do NOT use for current events — use web_search_tool instead.

    Args:
        topic: Topic to look up (e.g., "NVIDIA Corporation", "Large Language Models")

    Returns:
        Wikipedia article summary (first 1000 characters) with key facts
    """
    import wikipedia as wiki

    try:
        wiki.set_lang("en")
        page = wiki.page(topic, auto_suggest=True)
        summary = wiki.summary(topic, sentences=8, auto_suggest=True)

        return (
            f"Wikipedia: {page.title}\n"
            f"URL: {page.url}\n\n"
            f"{summary}"
        )
    except wiki.exceptions.DisambiguationError as e:
        # Try first suggestion
        try:
            summary = wiki.summary(e.options[0], sentences=6)
            return f"Wikipedia (disambiguated to '{e.options[0]}'):\n{summary}"
        except Exception:
            return f"Multiple Wikipedia pages found for '{topic}'. Options: {', '.join(e.options[:5])}"
    except wiki.exceptions.PageError:
        return f"No Wikipedia page found for '{topic}'. Try a more specific search term."
    except Exception as e:
        logger.warning("Wikipedia search failed for topic=%r: %s", topic[:50], e)
        raise
