# Generated by GitHub Copilot
# Azure Container Registry — stores Docker images

resource "azurerm_container_registry" "main" {
  name                = "acrresearch${var.suffix}"
  resource_group_name = var.resource_group_name
  location            = var.location
  sku                 = "Basic"
  admin_enabled       = false   # RBAC only — no admin password
  tags                = var.tags
}

output "login_server" { value = azurerm_container_registry.main.login_server }
output "id"           { value = azurerm_container_registry.main.id }

variable "resource_group_name" {}
variable "location" {}
variable "suffix" {}
variable "tags" { type = map(string) }
