# Generated by GitHub Copilot
# Azure Cache for Redis — rate limiter backend + semantic cache

resource "azurerm_redis_cache" "main" {
  name                = "redis-research-${var.suffix}"
  location            = var.location
  resource_group_name = var.resource_group_name
  capacity            = 0        # C0 — cheapest tier
  family              = "C"
  sku_name            = "Basic"
  non_ssl_port_enabled = false   # SSL only — security best practice (azurerm 4.x attribute)
  minimum_tls_version = "1.2"
  tags                = var.tags
}

output "connection_string" {
  value     = "rediss://:${azurerm_redis_cache.main.primary_access_key}@${azurerm_redis_cache.main.hostname}:6380/0"
  sensitive = true
}
output "id" { value = azurerm_redis_cache.main.id }

variable "resource_group_name" {}
variable "location" {}
variable "suffix" {}
variable "tags" { type = map(string) }
