# Generated by GitHub Copilot
"""
LangGraph StateGraph compilation.

This module builds and compiles the full research graph:

  START
    └─► supervisor_node      (creates research plan, interrupt() for H-I-L)
          ├─► web_research_node       ──┐
          ├─► market_data_node          ├─► synthesis_node ──► END
          └─► news_sentiment_node     ──┘

Key patterns used here:
  - RetryPolicy: every node retries on transient errors (LLM 5xx, network)
  - TimeoutPolicy: external API calls are capped — a hung yfinance call
    will not block the entire graph indefinitely
  - error_handler: if a research agent exhausts retries, it gracefully
    inserts a partial result so synthesis still runs with remaining data
  - PostgreSQL checkpointer: every state transition is persisted, so pod
    restarts or deployments don't lose in-progress research sessions
"""

from __future__ import annotations

import logging

from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.graph import CompiledGraph
from langgraph.types import RetryPolicy, TimeoutPolicy

from app.backend.agents.market_data import market_data_node, market_data_error_handler
from app.backend.agents.news_sentiment import news_sentiment_node, news_sentiment_error_handler
from app.backend.agents.state import AgentState
from app.backend.agents.supervisor import supervisor_node
from app.backend.agents.synthesis import synthesis_node
from app.backend.agents.web_research import web_research_node, web_research_error_handler

logger = logging.getLogger(__name__)

# ── Retry + Timeout policies ──────────────────────────────────────────────────
# Applied to all external-call nodes (tool-calling agents).
# Conservative: retry on network/5xx only — not on ValueError/LLM logic errors.
_RESEARCH_RETRY = RetryPolicy(
    initial_interval=1.0,
    backoff_factor=2.0,
    max_interval=30.0,
    max_attempts=3,
    jitter=True,
)

# External API timeout: 45s run, 10s idle (handles hung yfinance/Tavily calls)
_RESEARCH_TIMEOUT = TimeoutPolicy(
    run_timeout=45.0,
    idle_timeout=10.0,
)

# Supervisor only needs retry (no external API timeout needed)
_SUPERVISOR_RETRY = RetryPolicy(
    initial_interval=0.5,
    backoff_factor=2.0,
    max_attempts=2,
)


def build_research_graph(checkpointer: AsyncPostgresSaver) -> CompiledGraph:
    """
    Compile and return the research StateGraph with PostgreSQL checkpointer.

    The compiled graph is stateful — thread_id (session_id) maps to a
    checkpoint row in PostgreSQL, enabling resume after restarts and
    human-in-the-loop interrupts.
    """
    graph = StateGraph(AgentState)

    # ── Nodes ─────────────────────────────────────────────────────────────────
    graph.add_node(
        "supervisor",
        supervisor_node,
        retry_policy=_SUPERVISOR_RETRY,
    )
    graph.add_node(
        "web_research",
        web_research_node,
        retry_policy=_RESEARCH_RETRY,
        timeout=_RESEARCH_TIMEOUT,
        error_handler=web_research_error_handler,
    )
    graph.add_node(
        "market_data",
        market_data_node,
        retry_policy=_RESEARCH_RETRY,
        timeout=_RESEARCH_TIMEOUT,
        error_handler=market_data_error_handler,
    )
    graph.add_node(
        "news_sentiment",
        news_sentiment_node,
        retry_policy=_RESEARCH_RETRY,
        timeout=_RESEARCH_TIMEOUT,
        error_handler=news_sentiment_error_handler,
    )
    graph.add_node(
        "synthesis",
        synthesis_node,
        retry_policy=_SUPERVISOR_RETRY,
    )

    # ── Edges ─────────────────────────────────────────────────────────────────
    # supervisor fans out to all research agents in parallel via Send() API
    # (see supervisor_node for the Command + Send routing)
    graph.add_edge(START, "supervisor")

    # All research agents converge into synthesis (LangGraph fan-in)
    graph.add_edge("web_research", "synthesis")
    graph.add_edge("market_data", "synthesis")
    graph.add_edge("news_sentiment", "synthesis")

    graph.add_edge("synthesis", END)

    # Compile with PostgreSQL checkpointer
    # interrupt_before=["supervisor"] is NOT set here — the interrupt() call
    # is inside supervisor_node itself (more granular control).
    compiled = graph.compile(checkpointer=checkpointer)
    logger.info("Research graph compiled successfully")
    return compiled
