# Generated by GitHub Copilot
"""
Market Data Agent — fetches financial data via yfinance (free, no API key).

Specialises in:
  - Stock prices, historical performance, market cap
  - Company financials (revenue, earnings, P/E ratio)
  - Sector/industry comparisons

yfinance is an unofficial Yahoo Finance library. It's perfectly suitable
for a portfolio project — flag it in the ADR as: "For production with
real financial decisions, replace with Bloomberg/Refinitiv API."
"""

from __future__ import annotations

import logging
import time

from langchain_core.messages import HumanMessage
from langgraph.errors import NodeError
from langgraph.prebuilt import create_react_agent

from app.backend.agents.state import AgentFinding, AgentState
from app.backend.core.azure_clients import get_llm
from app.backend.tools.market_data import (
    get_stock_info_tool,
    get_stock_history_tool,
    get_company_financials_tool,
)

logger = logging.getLogger(__name__)

_MARKET_DATA_SYSTEM = """You are a financial data analyst. Your job is to gather 
and interpret financial data to answer research questions.

Instructions:
- Use get_stock_info to retrieve current stock price, market cap, P/E ratio
- Use get_stock_history to analyse price trends over a period
- Use get_company_financials to get revenue, earnings, balance sheet data
- Present data clearly with actual numbers and percentages
- Always state the date/period of the data
- Note: Data is from Yahoo Finance (delayed 15 min for free tier)
- If a ticker is not found, say so clearly — do not guess"""


async def market_data_node(state: AgentState) -> dict:
    """
    Market Data Agent node.

    Uses yfinance tools via LangChain create_react_agent. Returns financial
    data findings appended to agent_findings in AgentState.
    """
    logger.info("Market Data Agent starting for session=%s", state["session_id"])
    start = time.monotonic()

    plan = state.get("research_plan")
    query = plan["original_query"] if plan else state["user_query"]

    llm = get_llm()
    tools = [get_stock_info_tool, get_stock_history_tool, get_company_financials_tool]

    agent_executor = create_react_agent(
        model=llm,
        tools=tools,
        state_modifier=_MARKET_DATA_SYSTEM,
    )

    research_prompt = f"""Gather financial data relevant to this research query: {query}

If the query involves specific companies or stocks:
1. Get current stock info (price, market cap, P/E)
2. Get 3-month price history
3. Get recent financials (revenue, earnings)

If no specific company is mentioned, look for relevant market data (sector ETFs, 
market indices) or state that no direct financial data is available."""

    result = await agent_executor.ainvoke({
        "messages": [HumanMessage(content=research_prompt)]
    })

    final_message = result["messages"][-1]
    summary = final_message.content if hasattr(final_message, "content") else str(final_message)

    duration = round(time.monotonic() - start, 2)
    logger.info("Market Data Agent completed in %.1fs for session=%s", duration, state["session_id"])

    from app.backend.agents.state import Source
    finding = AgentFinding(
        agent_name="market_data",
        summary=summary,
        raw_data=summary,
        sources=[Source(
            title="Yahoo Finance",
            url="https://finance.yahoo.com",
            snippet="Financial data via yfinance library",
            source_type="financial",
        )],
        tokens_used=_estimate_tokens(result["messages"]),
        duration_seconds=duration,
        error=None,
    )

    return {"agent_findings": [finding]}


def market_data_error_handler(state: AgentState, error: NodeError) -> dict:
    """Graceful degradation when yfinance/market data is unavailable."""
    logger.error("Market Data Agent failed after retries: %s", error.error)
    finding = AgentFinding(
        agent_name="market_data",
        summary="Market data unavailable — financial data service temporarily unreachable.",
        raw_data="",
        sources=[],
        tokens_used=0,
        duration_seconds=0.0,
        error=str(error.error),
    )
    return {"agent_findings": [finding]}


def _estimate_tokens(messages: list) -> int:
    total_chars = sum(len(str(getattr(m, "content", ""))) for m in messages)
    return total_chars // 4
