# Generated by GitHub Copilot
"""
News + Sentiment Agent — gathers recent news and analyses sentiment via Tavily.

Focuses on:
  - Recent news headlines (last 7 days)
  - Public sentiment around topics/companies
  - Trend analysis from news volume and tone
"""

from __future__ import annotations

import logging
import time

from langchain_core.messages import HumanMessage
from langgraph.errors import NodeError
from langgraph.prebuilt import create_react_agent

from app.backend.agents.state import AgentFinding, AgentState
from app.backend.core.azure_clients import get_llm
from app.backend.tools.news_search import news_search_tool

logger = logging.getLogger(__name__)

_NEWS_SENTIMENT_SYSTEM = """You are a news analyst specialising in sentiment analysis.

Instructions:
- Use news_search to find recent news articles (last 7 days)
- Analyse the overall sentiment: Positive / Neutral / Negative / Mixed
- Identify the top 3-5 themes from the news
- Note any significant events, controversies, or announcements
- Quantify sentiment where possible (e.g., "8 of 10 articles positive")
- Be objective — report what the news says, not your opinion"""


async def news_sentiment_node(state: AgentState) -> dict:
    """
    News + Sentiment Agent node.

    Fetches recent news via Tavily's news endpoint and produces
    a sentiment analysis summary.
    """
    logger.info("News Sentiment Agent starting for session=%s", state["session_id"])
    start = time.monotonic()

    plan = state.get("research_plan")
    query = plan["original_query"] if plan else state["user_query"]

    llm = get_llm()
    tools = [news_search_tool]

    agent_executor = create_react_agent(
        model=llm,
        tools=tools,
        state_modifier=_NEWS_SENTIMENT_SYSTEM,
    )

    research_prompt = f"""Find and analyse recent news related to: {query}

Search for news from the last 7 days. Provide:
1. Overall sentiment (Positive/Negative/Neutral/Mixed)
2. Top 3-5 news themes or headlines
3. Any significant recent events
4. Sentiment trend (improving/declining/stable)"""

    result = await agent_executor.ainvoke({
        "messages": [HumanMessage(content=research_prompt)]
    })

    final_message = result["messages"][-1]
    summary = final_message.content if hasattr(final_message, "content") else str(final_message)

    sources = _extract_news_sources(result["messages"])
    duration = round(time.monotonic() - start, 2)
    logger.info("News Sentiment Agent completed in %.1fs for session=%s", duration, state["session_id"])

    finding = AgentFinding(
        agent_name="news_sentiment",
        summary=summary,
        raw_data=summary,
        sources=sources,
        tokens_used=_estimate_tokens(result["messages"]),
        duration_seconds=duration,
        error=None,
    )

    return {"agent_findings": [finding]}


def news_sentiment_error_handler(state: AgentState, error: NodeError) -> dict:
    """Graceful degradation when news search is unavailable."""
    logger.error("News Sentiment Agent failed after retries: %s", error.error)
    finding = AgentFinding(
        agent_name="news_sentiment",
        summary="News data unavailable — news search service temporarily unreachable.",
        raw_data="",
        sources=[],
        tokens_used=0,
        duration_seconds=0.0,
        error=str(error.error),
    )
    return {"agent_findings": [finding]}


def _extract_news_sources(messages: list) -> list:
    from app.backend.agents.state import Source
    sources = []
    for msg in messages:
        content = str(getattr(msg, "content", ""))
        if "http" in content and len(sources) < 5:
            sources.append(Source(
                title="News source",
                url="",
                snippet=content[:200],
                source_type="news",
            ))
    return sources


def _estimate_tokens(messages: list) -> int:
    total_chars = sum(len(str(getattr(m, "content", ""))) for m in messages)
    return total_chars // 4
