# Generated by GitHub Copilot
"""
AgentState — the single typed state object shared across all LangGraph nodes.

Every agent reads from and writes to this state. LangGraph's checkpointer
(PostgreSQL) serializes this after every node transition, enabling:
  - Session resume on pod restart
  - Human-in-the-loop interrupts
  - Time-travel debugging in LangFuse
"""

from __future__ import annotations

import operator
from typing import Annotated, Literal, TypedDict


class ResearchPlan(TypedDict):
    """Structured research plan produced by the Supervisor agent."""

    original_query: str
    sub_queries: list[str]  # broken-down sub-questions
    assigned_agents: list[str]  # which agents will execute
    estimated_duration_seconds: int
    estimated_tokens: int


class AgentFinding(TypedDict):
    """A single finding from one research agent."""

    agent_name: str
    summary: str
    raw_data: str  # agent's raw output before synthesis
    sources: list[Source]
    tokens_used: int
    duration_seconds: float
    error: str | None  # populated if agent partially failed


class Source(TypedDict):
    """A cited source from any agent."""

    title: str
    url: str
    snippet: str
    source_type: Literal["web", "news", "financial", "wikipedia"]


class AgentState(TypedDict):
    """
    Shared state across the entire LangGraph research workflow.

    Design principles:
    - All fields optional (TypedDict total=False where appropriate) to allow
      partial updates from each node.
    - agent_findings uses Annotated[list, operator.add] so parallel agents
      append their results without overwriting each other (LangGraph fan-in).
    - status is a Literal to make routing decisions explicit and type-safe.
    """

    # ── Input ─────────────────────────────────────────────────────────────────
    user_query: str
    user_id: str  # JWT 'oid' claim — used for rate limiting + cost tracking
    session_id: str  # LangGraph thread_id — maps to checkpointer key

    # ── Planning phase (Supervisor) ───────────────────────────────────────────
    research_plan: ResearchPlan | None

    # ── Human-in-the-loop gate ────────────────────────────────────────────────
    # interrupt() pauses here; resumes when user POSTs /research/{id}/approve
    plan_approved: bool

    # ── Research phase (parallel agents — fan-out via Send API) ──────────────
    # Annotated with operator.add: each agent APPENDS its finding, never overwrites.
    # This is the LangGraph pattern for parallel fan-in aggregation.
    agent_findings: Annotated[list[AgentFinding], operator.add]

    # ── Synthesis + Report phase ──────────────────────────────────────────────
    synthesis_notes: str  # cross-agent analysis before writing report
    final_report: str  # Markdown report with numbered citations
    citations: list[Source]  # deduplicated sources referenced in report

    # ── Metadata / Observability ──────────────────────────────────────────────
    total_tokens_used: int
    total_cost_usd: float  # estimated cost shown in UI
    error_message: str | None

    # ── Workflow status (drives conditional routing) ──────────────────────────
    status: Literal[
        "planning",
        "awaiting_approval",
        "researching",
        "synthesizing",
        "complete",
        "failed",
    ]
