# Generated by GitHub Copilot
"""
Supervisor Agent — the orchestrator node.

Responsibilities:
  1. Analyse the user's research query using GPT-4o (via LangChain AzureChatOpenAI)
  2. Produce a structured ResearchPlan (which sub-questions to ask, which agents to deploy)
  3. Call interrupt() — LangGraph pauses here, saves state to PostgreSQL,
     and the API returns the plan to the user for approval
  4. On resume (user approved): fan-out to all research agents in parallel
     using LangGraph's Send() API

Why interrupt() instead of a separate endpoint?
  The interrupt is baked into the graph node. The checkpointer ensures the
  exact graph state (plan, session_id, tokens so far) is persisted. The API
  just resumes the thread — no state reconstruction needed in application code.
"""

from __future__ import annotations

import json
import logging
import time

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langgraph.types import Command, Send, interrupt

from app.backend.agents.state import AgentState, ResearchPlan
from app.backend.core.azure_clients import get_llm

logger = logging.getLogger(__name__)

_SUPERVISOR_SYSTEM_PROMPT = """You are a senior research analyst. Given a research query, 
produce a structured JSON research plan that breaks the query into focused sub-questions 
and assigns each to the most suitable research agent.

Available agents and their strengths:
- web_research: Current events, news, web sources, general knowledge
- market_data: Financial data, stock prices, earnings, company financials  
- news_sentiment: News headlines, sentiment analysis, recent developments

Rules:
- Break complex queries into 2-4 focused sub-questions
- Assign each sub-question to the most relevant agent
- Multiple agents can work on the same query if relevant
- Estimate total tokens needed (rough estimate: 500-2000 per agent)

Return ONLY valid JSON matching this schema:
{
  "original_query": "string",
  "sub_queries": ["string"],
  "assigned_agents": ["web_research", "market_data", "news_sentiment"],
  "estimated_duration_seconds": 30,
  "estimated_tokens": 3000
}"""


async def supervisor_node(state: AgentState) -> Command:
    """
    Supervisor node: plan → interrupt (H-I-L) → fan-out to research agents.

    LangGraph calls this as an async node. The interrupt() call causes the
    graph to pause and persist state. The API resumes the thread when the
    user approves the plan via POST /research/{session_id}/approve.
    """
    logger.info("Supervisor starting for session=%s query=%r", state["session_id"], state["user_query"][:80])
    start = time.monotonic()

    llm = get_llm()
    parser = JsonOutputParser()

    prompt = ChatPromptTemplate.from_messages([
        SystemMessage(content=_SUPERVISOR_SYSTEM_PROMPT),
        HumanMessage(content=f"Research query: {state['user_query']}"),
    ])

    chain = prompt | llm | parser
    plan_dict: dict = await chain.ainvoke({})

    research_plan = ResearchPlan(
        original_query=state["user_query"],
        sub_queries=plan_dict.get("sub_queries", [state["user_query"]]),
        assigned_agents=plan_dict.get("assigned_agents", ["web_research", "market_data", "news_sentiment"]),
        estimated_duration_seconds=plan_dict.get("estimated_duration_seconds", 30),
        estimated_tokens=plan_dict.get("estimated_tokens", 3000),
    )

    logger.info(
        "Research plan created: agents=%s estimated_tokens=%d",
        research_plan["assigned_agents"],
        research_plan["estimated_tokens"],
    )

    # ── Human-in-the-loop interrupt ───────────────────────────────────────────
    # LangGraph saves state to PostgreSQL here and pauses execution.
    # The API endpoint reads this plan from state and returns it to the client.
    # When user calls POST /research/{id}/approve, the graph resumes from here.
    approval_response = interrupt({
        "type": "plan_approval",
        "plan": research_plan,
        "message": "Review and approve the research plan before agents begin working.",
    })

    # If user rejected the plan (approval_response = {"approved": False})
    if not approval_response.get("approved", True):
        logger.info("Research plan rejected by user for session=%s", state["session_id"])
        return Command(
            update={
                "status": "failed",
                "error_message": "Research plan was rejected by user.",
            },
        )

    # ── Fan-out: dispatch all assigned agents in parallel via Send() ──────────
    # LangGraph's Send() API runs multiple nodes concurrently.
    # Each agent receives the full state plus the research plan.
    agents_to_run = research_plan["assigned_agents"]
    duration = round(time.monotonic() - start, 2)
    logger.info("Fanning out to %d agents in parallel: %s", len(agents_to_run), agents_to_run)

    return Command(
        update={
            "research_plan": research_plan,
            "plan_approved": True,
            "status": "researching",
        },
        goto=[
            Send(agent_name, {**state, "research_plan": research_plan, "plan_approved": True})
            for agent_name in agents_to_run
        ],
    )
