# Generated by GitHub Copilot
"""
Web Research Agent — searches the public web via Tavily API.

This agent is a LangGraph ReAct agent: it calls the LLM, the LLM decides
which tool to call (web_search), the tool result comes back, the LLM
synthesises findings. LangChain's create_react_agent() handles the loop.

Error handler: if this agent exhausts retries (e.g., Tavily is down),
web_research_error_handler inserts a partial result with error details
so synthesis can still run with the other agents' data.
"""

from __future__ import annotations

import logging
import time

from langgraph.errors import NodeError
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import HumanMessage

from app.backend.agents.state import AgentFinding, AgentState
from app.backend.core.azure_clients import get_llm
from app.backend.tools.web_search import web_search_tool
from app.backend.tools.wikipedia import wikipedia_tool

logger = logging.getLogger(__name__)

_WEB_RESEARCH_SYSTEM = """You are a web research specialist. Your job is to search the web
and Wikipedia for accurate, current information to answer research questions.

Instructions:
- Use web_search for current events, recent developments, and general information
- Use wikipedia_search for factual background, definitions, and historical context
- Synthesise findings into a clear, factual summary (3-5 paragraphs)
- List all sources you used
- Focus on accuracy — if you are not certain, say so
- Do NOT speculate or add information not found in your searches"""


async def web_research_node(state: AgentState) -> dict:
    """
    Web Research Agent node.

    Uses LangChain's create_react_agent (ReAct loop) with Tavily + Wikipedia tools.
    Returns a partial AgentState update with agent_findings appended.
    """
    logger.info("Web Research Agent starting for session=%s", state["session_id"])
    start = time.monotonic()

    plan = state.get("research_plan")
    query = plan["original_query"] if plan else state["user_query"]
    sub_queries = plan["sub_queries"] if plan else [query]

    llm = get_llm()
    tools = [web_search_tool, wikipedia_tool]

    # create_react_agent is a LangChain prebuilt that handles the tool-call loop
    agent_executor = create_react_agent(
        model=llm,
        tools=tools,
        state_modifier=_WEB_RESEARCH_SYSTEM,
    )

    # Build the research prompt from sub-queries relevant to this agent
    research_prompt = f"""Research the following:

Main query: {query}

Sub-questions to address:
{chr(10).join(f"- {q}" for q in sub_queries[:3])}

Search the web and Wikipedia. Provide a thorough summary with all sources."""

    result = await agent_executor.ainvoke({
        "messages": [HumanMessage(content=research_prompt)]
    })

    # Extract final answer and any tool call details
    final_message = result["messages"][-1]
    summary = final_message.content if hasattr(final_message, "content") else str(final_message)

    # Extract sources from tool call results in message history
    sources = _extract_sources_from_messages(result["messages"])

    duration = round(time.monotonic() - start, 2)
    logger.info("Web Research Agent completed in %.1fs for session=%s", duration, state["session_id"])

    finding = AgentFinding(
        agent_name="web_research",
        summary=summary,
        raw_data=summary,
        sources=sources,
        tokens_used=_estimate_tokens(result["messages"]),
        duration_seconds=duration,
        error=None,
    )

    return {"agent_findings": [finding]}


def web_research_error_handler(state: AgentState, error: NodeError) -> dict:
    """
    Called when web_research_node exhausts all retries.

    Inserts a partial finding with the error details so synthesis
    can still run with data from other agents.
    """
    logger.error("Web Research Agent failed after retries: %s", error.error)
    finding = AgentFinding(
        agent_name="web_research",
        summary="Web research unavailable — service temporarily unreachable.",
        raw_data="",
        sources=[],
        tokens_used=0,
        duration_seconds=0.0,
        error=str(error.error),
    )
    return {"agent_findings": [finding]}


def _extract_sources_from_messages(messages: list) -> list:
    """Extract source URLs from Tavily tool call results in message history."""
    from app.backend.agents.state import Source
    sources = []
    for msg in messages:
        if hasattr(msg, "content") and isinstance(msg.content, str):
            # Tavily returns results with URLs in structured format
            # This is a best-effort extraction from the message text
            if "http" in msg.content:
                sources.append(Source(
                    title="Web source",
                    url="",
                    snippet=msg.content[:200],
                    source_type="web",
                ))
    return sources[:5]  # cap at 5 sources


def _estimate_tokens(messages: list) -> int:
    """Rough token estimate based on total message character count."""
    total_chars = sum(
        len(str(getattr(m, "content", ""))) for m in messages
    )
    return total_chars // 4  # ~4 chars per token
