# Generated by GitHub Copilot
"""
Unit tests for AgentState — verifies the TypedDict structure and
the Annotated[list, operator.add] fan-in pattern used by parallel agents.
"""

import operator
from typing import get_type_hints

import pytest

from app.backend.agents.state import AgentFinding, AgentState, ResearchPlan, Source


def test_agent_state_fields_exist() -> None:
    """AgentState must have all required fields for LangGraph to work."""
    hints = get_type_hints(AgentState, include_extras=True)
    required = {
        "user_query", "user_id", "session_id", "research_plan",
        "plan_approved", "agent_findings", "synthesis_notes",
        "final_report", "citations", "total_tokens_used",
        "total_cost_usd", "error_message", "status",
    }
    assert required.issubset(hints.keys()), f"Missing fields: {required - hints.keys()}"


def test_agent_findings_uses_operator_add() -> None:
    """
    agent_findings must use Annotated[list, operator.add] so parallel
    agents append results without overwriting each other.
    This is the key LangGraph fan-in pattern.
    """
    import typing
    hints = get_type_hints(AgentState, include_extras=True)
    findings_hint = hints["agent_findings"]

    # Verify it's an Annotated type with operator.add as the reducer
    args = typing.get_args(findings_hint)
    assert len(args) == 2, "agent_findings must be Annotated[list, reducer]"
    assert args[1] is operator.add, "reducer must be operator.add for fan-in"


def test_agent_finding_structure() -> None:
    """AgentFinding TypedDict must have all expected fields."""
    hints = get_type_hints(AgentFinding)
    required = {"agent_name", "summary", "raw_data", "sources", "tokens_used", "duration_seconds", "error"}
    assert required.issubset(hints.keys())


def test_source_structure() -> None:
    """Source TypedDict must have all expected fields."""
    hints = get_type_hints(Source)
    required = {"title", "url", "snippet", "source_type"}
    assert required.issubset(hints.keys())
