# Generated by GitHub Copilot
"""Unit tests for Pydantic request/response models."""

import pytest
from pydantic import ValidationError

from app.backend.models.research import (
    PlanApprovalRequest,
    ResearchRequest,
    ResearchResultResponse,
)


def test_research_request_valid() -> None:
    req = ResearchRequest(query="What is the competitive position of NVIDIA in the AI chip market?")
    assert req.query.startswith("What")


def test_research_request_too_short() -> None:
    with pytest.raises(ValidationError):
        ResearchRequest(query="short")  # min_length=10


def test_research_request_too_long() -> None:
    with pytest.raises(ValidationError):
        ResearchRequest(query="x" * 1001)  # max_length=1000


def test_plan_approval_approved() -> None:
    req = PlanApprovalRequest(approved=True)
    assert req.approved is True
    assert req.feedback is None


def test_plan_approval_rejected_with_feedback() -> None:
    req = PlanApprovalRequest(approved=False, feedback="Too broad")
    assert req.approved is False
    assert req.feedback == "Too broad"


def test_research_result_response_defaults() -> None:
    resp = ResearchResultResponse(
        session_id="test-id",
        query="test query",
        final_report="# Report",
        citations=[],
        total_tokens_used=1000,
        total_cost_usd=0.005,
        agents_used=["web_research", "market_data"],
    )
    assert resp.status == "complete"
