# Generated by GitHub Copilot
"""Unit tests for Settings — verifies Pydantic parsing and feature flags."""

import pytest

from app.backend.core.config import Settings


def test_settings_defaults() -> None:
    s = Settings()
    assert s.app_env == "development"
    assert s.log_level == "INFO"
    assert s.rate_limit_per_minute == 20
    assert s.enable_auth is False
    assert s.enable_cache is True


def test_postgres_dsn_built_from_parts() -> None:
    s = Settings(
        postgres_host="myhost",
        postgres_port=5432,
        postgres_user="user",
        postgres_password="pass",
        postgres_db="db",
    )
    assert "myhost" in s.postgres_dsn
    assert "user" in s.postgres_dsn
    assert "db" in s.postgres_dsn


def test_allowed_origins_parsed_from_comma_string() -> None:
    s = Settings(allowed_origins="http://localhost:3000,http://localhost:5173")
    assert "http://localhost:3000" in s.allowed_origins
    assert "http://localhost:5173" in s.allowed_origins


def test_is_production_false_for_development() -> None:
    s = Settings(app_env="development")
    assert s.is_production is False


def test_is_production_true() -> None:
    s = Settings(app_env="production")
    assert s.is_production is True
